import { existsSync } from "node:fs";
import { mkdir, writeFile, readFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { parseOpenApi, generatedFileName, generatedToolSource } from "../openapi/index.js";

const usage = `mcp-builder <command>\n\nCommands: init [name], dev, build, inspect, validate, test, generate <openapi.json|docker>, doctor`;
const pkg = async () => JSON.parse(await readFile(join(process.cwd(), "package.json"), "utf8")) as { scripts?: Record<string, string> };
async function init(name = "my-mcp-server") { const root = resolve(process.cwd(), name); if (existsSync(root)) throw new Error(`${name} already exists`); for (const directory of ["src/tools", "src/resources", "src/prompts", "src/middleware", "tests"]) await mkdir(join(root, directory), { recursive: true }); await Promise.all([
  writeFile(join(root, "package.json"), JSON.stringify({ name, private: true, type: "module", scripts: { dev: "tsx watch src/index.ts", build: "tsup src/index.ts --format esm", start: "node dist/index.js" }, dependencies: { "@agent-utils/mcp-builder": "latest" }, devDependencies: { tsx: "latest", tsup: "latest", typescript: "latest" } }, null, 2) + "\n"),
  writeFile(join(root, "tsconfig.json"), JSON.stringify({ compilerOptions: { target: "ES2022", module: "NodeNext", moduleResolution: "NodeNext", strict: true }, include: ["src"] }, null, 2) + "\n"),
  writeFile(join(root, "mcp.config.ts"), `import { defineMCPConfig } from "@agent-utils/mcp-builder";\nexport default defineMCPConfig({ name: "${name}", version: "0.1.0", transport: "stdio", tools: "./src/tools" });\n`),
  writeFile(join(root, "src/index.ts"), `import { createMCPServer } from "@agent-utils/mcp-builder";\nconst server = createMCPServer({ name: "${name}", version: "0.1.0" });\nserver.tool("hello", { description: "Say hello", input: { name: "string" }, handler: ({ name }) => ({ message: \`Hello, \${name}!\` }) });\nserver.start();\n`),
  writeFile(join(root, "README.md"), `# ${name}\n\nAn MCP server built with @agent-utils/mcp-builder.\n`)
]); console.log(`Created ${root}`); }
async function generate(source: string, args: string[]) { if (source === "docker") { await writeFile(join(process.cwd(), "Dockerfile"), "FROM node:20-alpine\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci --omit=dev\nCOPY dist ./dist\nCMD [\"node\", \"dist/index.js\"]\n"); return console.log("Created Dockerfile"); } const doc = JSON.parse(await readFile(resolve(source), "utf8")); const include = args.find((arg) => arg.startsWith("--include="))?.slice(10); const exclude = args.find((arg) => arg.startsWith("--exclude="))?.slice(10); const folder = join(process.cwd(), "src/tools"); await mkdir(folder, { recursive: true }); for (const operation of parseOpenApi(doc, { include: include ? new RegExp(include.replaceAll("*", ".*")) : undefined, exclude: exclude ? new RegExp(exclude.replaceAll("*", ".*")) : undefined })) await writeFile(join(folder, generatedFileName(operation)), generatedToolSource(operation)); console.log("Generated tools in src/tools"); }
async function doctor() { const checks = [{ name: "Node.js >=18.17", ok: Number(process.versions.node.split(".")[0]) >= 18 }, { name: "package.json", ok: existsSync("package.json") }, { name: "mcp.config.ts", ok: existsSync("mcp.config.ts") }]; checks.forEach((check) => console.log(`${check.ok ? "✓" : "✗"} ${check.name}`)); if (checks.some((check) => !check.ok)) process.exitCode = 1; }
export async function runCli(args = process.argv.slice(2)) { const [command, ...rest] = args; if (!command || command === "--help") return console.log(usage); if (command === "init") return init(rest[0]); if (command === "generate" && rest[0]) return generate(rest[0], rest.slice(1)); if (command === "doctor") return doctor(); if (["dev", "build", "test"].includes(command)) { const data = await pkg(); const script = data.scripts?.[command]; if (!script) throw new Error(`No '${command}' script found in package.json`); console.log(`Run: npm run ${command}`); return; } if (command === "validate") { if (!existsSync("mcp.config.ts")) throw new Error("mcp.config.ts is missing"); return console.log("Configuration looks valid. Run npm run typecheck for full validation."); } if (command === "inspect") return console.log("Inspector API: start your server with HTTP transport, then visit GET /health and POST /mcp."); throw new Error(`Unknown command '${command}'\n\n${usage}`); }
if (import.meta.url === `file://${process.argv[1]}`) runCli().catch((error: Error) => { console.error(`mcp-builder: ${error.message}`); process.exitCode = 1; });
